RustCrypto/RSA

.travis.yml, Cargo.toml, README.md, src/lib.rs
Not sure about the minimum supported Rust version for CI, for now it's 1.27.
=> Minor post-transfer changes

src/algorithms.rs, src/key.rs, src/lib.rs
When decrypting, care has to be taken to ensure that negative numbers are brought back into the positive range. 
In most cases the `if < 0 then += prime` was enough, but if the number was more negative than the prime, we ended up with still a negative number. So this was changed to use a `while` statement, which ensures the right thing always happens. 
Fixes #2
=> fix(decryption): ensure values are positive 

Cargo.toml, src/danger.rs, src/internals.rs, src/key.rs, src/lib.rs, src/pkcs1v15.rs
I've split blinding and unblinding into their own public functions.   
This relates to #9 - instead of implementing a full blind-signing protocol in this crate, we just expose the `blind` and `unblind` functions to make building such a protocol easier. 
In addition I've re-exported the raw RSA functions into a new module called 'danger'.   The intention here is to allow other crates that are creating custom RSA schemes to access raw RSA functions, but to ward off casual users.
=> Splitting blind and unblind into their own functions, exposing raw RSA functions via `internals` module

src/key.rs
While generally passing around RSAPrivateKey as a `PublicKey` trait is optimal, there are some instances where you want to deal in concrete types and not be passing around the secret private data.  This PR adds a utility `extract_public()` method for RSAPrivateKey for those circumstances.
=> adds the to_public_key() method for RSAPrivateKey

Cargo.toml, benches/key.rs, src/algorithms.rs, src/internals.rs, src/key.rs, src/lib.rs, src/pkcs1v15.rs
This pull request does two things:
1. Moves to the 2018 edition and applies 2018 edition idioms
2. Runs rustfmt
The application of rustfmt makes this PR look scarier than it is, so you may want to checkout 558d34f, review the diff at 558d34f, and then and run rustfmt yourself.
=> Moving to 2018 edition

src/lib.rs
BigUint is part of the public API surface of RSA. As such, I think it's a good idea to reexport it. It avoids forcing the user to add a dependency on num-bigint-dig when importing pubkeys or privkeys.
=> Reexport biguint

.travis.yml, Cargo.toml, README.md, src/key.rs, src/lib.rs
bumps msr to 1.36, given smallvec dependency
=> feat: update dependencies

src/errors.rs, src/key.rs
Currently, `RSAPrivateKey::precompute` panic when Chinese remainder theorem can't be applied.
This is a frequent issue with openssl / mbedtls generated private keys. See issue https://github.com/RustCrypto/RSA/issues/30.
However, it is not required to be called to properly create signatures.
This PR
- modify the `precompute` method to return a `Result` instead of panicking
- ignore the result of the `precompute` call when building a RSAPrivateKey using `from_components`. That is if Chinese remainder theorem can't be applied, there is no precomputed data, but no panic either. The private key can still be used for signing operations.
This isn't a breaking change as long as user code doesn't `#[deny(unused_must_use)]` when calling `precompute`.
=> fix: make precompute optional instead of panicking on invalid coeff

Cargo.toml, src/errors.rs, src/key.rs, src/lib.rs, src/parse.rs
Adds simple functions for parsing `pkcs1` and `pkcs8` encoded keys and a `pem` feature that re-exports the `pem` crate with `TryFrom` implementations.
The `TryFrom` implementations will auto-detect `pkcs1` or `pkcs8` via the header tags.
```rust
let pem = rsa::pem::parse(private_key_pem)?;
let private_key = RSAPrivateKey::try_from(pem)?;
let pem = rsa::pem::parse(public_key_pem)?;
let public_key= RSAPublicKey::try_from(pem)?;
```
Or, manually:
```rust
// -----BEGIN RSA PRIVATE KEY-----
let private_key = rsa::parse_private_key_pkcs1(pkcs1_private_key_base64_decoded)?;
// -----BEGIN RSA PUBLIC KEY-----
let public_key = rsa::parse_public_key_pkcs1(pkcs1_public_key_base64_decoded)?;
// -----BEGIN PRIVATE KEY-----
let private_key = rsa::parse_private_key_pkcs8(pkcs8_private_key_base64_decoded)? …
```
=> Add parsing for pkcs1 and pkcs8 encoded rsa keys

src/key.rs, src/pkcs1v15.rs
A small refactor so that public and private keys are both generic inside the PKCS1v15 implementation.
Part of #34.
=> pkcs1v15: Make decrypt() and sign() generic over PrivateKey

src/algorithms.rs, src/key.rs
This commit adds a function to `rsa::algorithms` called `generate_multi_prime_key_with_exp` which allows the caller to specify a custom value for the public key exponent.
This commit also adds a convenience routine to `rsa::RSAPrivateKey` called `new_with_exp` which allows the caller to specify the custom value for the public key exponent as part of `rsa::RSAPrivateKey` constructor.
Exposing the public key exponent matches an OpenSSL call `openssl::rsa::generate_with_e` which is useful in certain settings such when generating the signing keys for SGX enclaves.
Lemme know what y'all think about this change! Oh, and if you feel the PR could be improved upon or some bits are missing, lemme know and I'll be happy to iterate through with you until we get something that's mergeable!
=> feat: allow for custom public exponent value in keygen

.github/workflows/ci.yml, Cargo.toml, src/algorithms.rs, src/encode.rs, src/errors.rs, src/internals.rs, src/key.rs, src/lib.rs, src/oaep.rs, src/padding.rs, src/parse.rs, src/pkcs1v15.rs, src/pss.rs, src/raw.rs
Blocked on https://github.com/dignifiedquire/num-bigint/pull/12
Missing: docs, tests and a way to avoid having base64 break our builds to rust-lang/cargo#4866.
=> feat: nostd, core+alloc support

README.md
The private key is assigned to `priv_key` but then `&private_key` is passed to `RSAPublicKey::from`.
=> Fix variable name in README

src/encode.rs
Reasons for the incompatibility are stated in [this comment](https://github.com/RustCrypto/RSA/issues/63#issuecomment-696336493)
Changes were made according to [RFC 3447; Appendix A.1.2](https://tools.ietf.org/html/rfc3447#appendix-A.1.2)
Closes #63
=> feat: improve OpenSSL compatibility for encoding and decoding keys

Cargo.toml
=> Lock `zeroize` to v1.3

src/key.rs, src/lib.rs, src/parse.rs
These are no longer needed as of the 2018 edition
=> Remove `extern crate` directives

src/key.rs, src/oaep.rs, src/padding.rs
This pull request adds a new field to the OAEP padding to allow for a different hash function for the MGF mask function. This is especially needed, when trying to be compatible with other algorithms, more specifically the `AndroidKeyStore`. The `AndroidKeyStore` only supports RSA encryption with SHA256 and SHA1 for the MGF mask function.
For compatibility the existing functions were adjusted to replicate the previous behaviour to use the same hash function.
To the OAEP-Padding  two new functions `new_oaep_with_mgf_hash` and `new_oaep_with_mgf_hash_with_labe` were added to allow specifying the MGF hash function.
=> Add possibility to allow a different hash function for MGF mask function

src/encode.rs
as per the RFC 8017 [1], the NULL parameter MUST be present if the OID in
AlgorithmIdentifier is `rsaEncryption`. this commit adds an explicit
NULL to the AlgorithmIdentifier so that RSA keys encoded by this crate
are compliant to the RFC:
> The object identifier rsaEncryption identifies RSA public and private
> keys as defined in Appendices A.1.1 and A.1.2.  The parameters field
> has associated with this OID in a value of type AlgorithmIdentifier
> SHALL have a value of type NULL.
[1] https://tools.ietf.org/html/rfc8017#appendix-A
fixes #91
=> add NULL parameter to AlgorithmIdentifier of encoded keys

README.md
This helps address #29 a little from a documentation perspective.
=> docs(readme): add Note About Key Generation Speed

README.md
I saw a merge of #61 and thought that integrating the limited optimization instruction I found would be a nice idea.
=> docs(readme): only optimizing num-bigint-dig is enough to unlock most speedups

README.md
[Rendered](https://github.com/RustCrypto/RSA/blob/fc9c69b9882489c7cd6ae07753c2682f4baad1af/README.md)
The `:emoji:` tags are part of GitHub Flavored Markdown and don't render correctly on https://crates.io/crates/rsa
Examples:
With Unicode emoji, these should render correctly
=> README.md: use Unicode emoji

src/key.rs
It would be great for the RsaPublicKey to derive the Hash trait.
All the internal fields of RsaPublicKey already implement the Hash trait, it is enough to automatically derive.
By doing so, it becomes possible to store RsaPublicKey e.g. in an HashSet.
=> feat: derive Hash for `RsaPublicKey`

Cargo.toml, src/key.rs
This also speeds up `check_public` by about 30%, as the compiler can optimize it by taking into account the constant values.
=> refactor: remove `lazy_static` dependency

src/key.rs
Small helper, which is useful for when you want to build upon this crate.
Currently, I am using a hacky workaround for this by serializing and deserializing, since deserializing does not precompute values automatically.
=> feat(key): add fn to clear precomputed values on RsaPrivateKey

.github/workflows/ci.yml, Cargo.toml, README.md, src/encoding.rs, src/key.rs, src/lib.rs, tests/pkcs1.rs, tests/pkcs8.rs
Updates the `pkcs1` and `pkcs8` crates to their latest versions.
These releases reversed the blanket impl relationship between the traits in the two respective crates.
The names of the traits have changed:
- `From*Key` => `Decode*Key` (e.g. `DecodePrivateKey`)
- `To*Key` => `Encode*Key` (e.g. `EncodePrivateKey`).
Previously there was a blanket impl of `pkcs8` traits for the `pkcs1` crates, e.g. `DecodePrivateKey` was impl'd for `DecodeRsaPrivateKey`.
This relationship has been reversed in the latest releases, and as such this commit now implements the `pkcs8` traits instead of the `pkcs1` traits (even though this internally involves decoding a PKCS#1 document as part of PKCS#8 decoding).
The reasoning is this was necessary to make it possible for traits for multiple formats to have …
=> Bump `pkcs1` => v0.3, `pkcs8` => v0.8; MSRV 1.56

Cargo.toml, src/key.rs
The `zeroize_derive` crate has quite a few dependencies, and in particular `syn` is a fairly large one with not-insignificant compile times.
Together with dignifiedquire/num-bigint#35, this will remove the following dependencies from the dependency tree:
- `proc-macro2`
- `quote`
- `syn`
- `synstructure`
- `zeroize_derive`
=> Impl `zeroize` without using `zeroize_derive`

.github/workflows/ci.yml, Cargo.toml
=> feat: update to rust edition 2021

.github/workflows/ci.yml, Cargo.toml, README.md, benches/key.rs, src/algorithms.rs, src/internals.rs, src/key.rs, src/lib.rs, src/oaep.rs, src/padding.rs, src/pkcs1v15.rs, src/pss.rs, src/raw.rs, tests/pkcs1.rs, tests/pkcs8.rs
`rand` is still a dev-dependency and used in code examples.
Also removes dependency on `rand_xorshift`, `base64`, and `hex`. Removes the `alloc`, which was effectively useless.
Closes #115
=> Replace rand dependency with rand_core

Cargo.toml, src/key.rs, src/lib.rs, src/pkcs1v15.rs, src/pss.rs
Closes #149 
Examples (i.e. doctests) continue to use `ThreadRng`. They are intentionally kept nondeterministic since users should prefer using `ThreadRng` if possible.
=> Remove nondeterministic tests

.github/workflows/ci.yml, src/algorithms.rs, src/lib.rs
- Fixes some broken links to the `pkcs1`/`pkcs8` crate traits
- Fixes other rustdoc warnings
- Adds rustdoc CI job to ensure docs build without warnings
=> Fix rustdoc warnings and add rustdoc CI

src/encoding.rs, src/key.rs
This method is useful for key serialization formats and is internally useful within the context of the PKCS#1/PKCS#8 implementations.
Externally I'm working on adding support to the `ssh-key` crate. I could implement this same thing by pulling in `num_bigint_dig::ModInverse`, it'd be a lot easier if this purpose-dedicated method were available.
=> Add `RsaPrivateKey::crt_coefficient`

.github/workflows/ci.yml, Cargo.toml, README.md, src/encoding.rs, tests/pkcs1.rs, tests/pkcs8.rs
This updates both the `pkcs1` and `pkcs8` crates to their latest version.
It mainly involves renaming `PublicKeyDocument` => `Document`, `PrivateKeyDocument` => `SecretDocument` and `UIntBytes` => `UIntRef`.
=> Bump `pkcs1` => 0.4, `pkcs8` => 0.9

Cargo.toml
Includes `pkcs1` v0.4 and `pkcs8` v0.9 updates (#162), which are a breaking change
=> v0.7.0-pre

src/errors.rs, src/key.rs
This constructor accepts a configurable maximum key size which can be used in applications that need to deal with unusually large RSA public keys, such as OpenPGP.
With the ability to configure an upper limit, this makes it possible to lower the default maximum key size to 4096-bits, which is a reasonable upper limit for most applications.
Fixes #166
=> Add `RsaPublicKey::new_with_max_size`; 4096-bit default max

Cargo.toml, src/dummy_rng.rs, src/errors.rs, src/key.rs, src/lib.rs, src/pkcs1v15.rs, src/pss.rs
Refactor the `rsa` crate to use the API defined by the `signature` crate.
This adds `pss` and `pkcs1v15` modules, each of them providing `Signature`, `Verifier` and `Signer`/`RandomizedSigner` implementations.
=> Implement Signer/Verifier/Signature interfaces for the RSA signatures

src/key.rs, src/padding.rs, src/pss.rs
A fix for #172 , implementation of verify-only PSS padding schema
=> Implement verify-only PSS PaddingScheme

.gitattributes, tests/pkcs1.rs, tests/pkcs8.rs
The checked-in files use Unix-style line endings, so use `LineEnding::LF` in tests, rather than `Default::default` (which uses OS-specific line endings.
Closes #175.
=> Fix PKCS#1/PKCS#8 line endings on Windows

Cargo.toml, src/algorithms.rs, src/hash.rs, src/lib.rs, src/pkcs1v15.rs, src/pss.rs
=> Update RSA signature traits implementations

src/lib.rs
Remove a leftover use rsa::Hash part from the crate's doc-tests.
=> Drop unused Hash usage from doc-tests

src/pkcs1v15.rs, src/pss.rs
Implement Deref<Target = [u8]> for the Signature types to allow automatically dereferencing Signature as byte slices.
=> Allow dereferencing Signature types

src/internals.rs, src/key.rs, src/raw.rs
Drop boilerplate code which implements traits for references to key types. The code can use references directly.
=> Drop reference boilerplate code

src/pkcs1v15.rs, src/pss.rs
- added Clone and Debug for SigningKey & VerifyingKey of pss and pkcs1v15
This is useful, and keep the counterpart in [ecdsa](https://github.com/RustCrypto/signatures/tree/master/ecdsa)
=> Derive Clone and Debug for vk and sk

Cargo.toml, src/pkcs1v15.rs
Implement PrehashSigner and PrehashVerifier traits for PKCS1v15 structures.
=> feat: iplement hazmat signature traits for PKCS1v15 keys

Cargo.toml
The crate is now using the `PrehashSigner`/`PrehashVerifier` traits, which were added in `signature` v1.6.1.
However, that release was also yanked, so this commit pins to 1.6.2.
=> Fix `signature` version requirement

.github/workflows/ci.yml
Updates the action [`actions/checkout`](https://github.com/actions/checkout) to v3, the latest major release.
This should basically be backwards compatible, so I expect no breakage.
=> chore: update actions used in GitHub Actions workflows

.github/dependabot.yml
Extend Dependabot configuration to automatically open PRs for outdated actions.
Inspired by https://github.com/RustCrypto/hashes/pull/410#issuecomment-1252658128.
=> chore: extend Dependabot configuration for GitHub Actions updates

Cargo.toml, src/pss.rs
Implement PrehashSigner and PrehashVerifier traits for PSS key structures.
=> feat: iplement hazmat signature traits for PSS keys

src/pkcs1v15.rs, src/pss.rs
Implement key -> der conversion for public keys.
=> RSA: implement EncodePublicKey for VerifyingKeys

src/key.rs
Constructor for `RsaPublicKey` which bypasses all checks around the modulus and public exponent size.
Closes #199.
=> Add `RsaPublicKey::new_unchecked`

src/key.rs, src/padding.rs
It's more convenient for users.
Fix #214
=> padding: ensure PaddingScheme is Send and Sync

src/algorithms.rs, src/errors.rs, src/key.rs, src/lib.rs, src/oaep.rs, src/padding.rs, src/pkcs1v15.rs, src/pss.rs
Several types and methods were missing documentation.
This commit adds document and enables warnings for `missing_docs`.
Additionally it updates all references to PKCS#1 RFCs to use RFC8017, which documents the latest version of PKCS#1.
cc @lumag
=> Add missing rustdoc comments; enable `missing_docs` lint

src/key.rs
I need access to these values in order to store a custom private key format, this is preventing me from switching away from openssl
=> Make PrecomputedValues public

src/lib.rs, src/pkcs1v15.rs, src/pss.rs
Makes each code example a linkable section of the rustdoc.
Uses these links to link from individual modules to code examples in the toplevel rustdoc.
=> Linkify code examples in rustdoc

src/lib.rs
It's needed to use the `SigningKey`/`VerifyingKey` types in the `pkcs1v15` and `pss` modules.
Also updates the code examples to use the re-export.
=> Re-export `signature` crate

Cargo.toml
Now that https://github.com/dignifiedquire/num-bigint/pull/42 has landed it is no longer needed.
=> Remove `minimal-versions` workaround

Cargo.toml, src/algorithms.rs, src/key.rs, src/lib.rs, src/pkcs1v15.rs, src/pss.rs
Rework the crate to implement traits from the preview of the signature crate. Use Vec<u8> as Self::Repr type.
Note: I'm yet to see how will this impact the code in my projects. But for the evaluation I'd first need `ecdsa` / `p384` to be updated.
cc @tarcieri @dignifiedquire
=> feat: switch to version 2.0 (pre) of the  signature crate

src/lib.rs
The only public type in the `padding` module is `PaddingScheme`, which is already re-exported from the toplevel.
There is no rustdoc documentation at the top of the module, and therefore little value in having `PaddingScheme` available as both `rsa::PaddingScheme` and `rsa::padding::PaddingScheme`.
=> Make `padding` module private

benches/key.rs, src/key.rs, src/lib.rs, src/oaep.rs, src/padding.rs, src/pkcs1v15.rs, src/pss.rs
As proposed in #226, splits up the `PaddingScheme` enum into four structs, named after the previous variants of the struct (adopting capitalization from the Rust API guidelines):
- `oaep::Oaep`
- `pkcs1v15::{Pkcs1v15Encrypt, Pkcs1v15Sign}`
- `pss::Pss`
All of these are re-exported from the toplevel.
Each of these structs impls one or more of the following traits:
- `PaddingScheme`: used for encryption
- `SignatureScheme`: used for signing
The `PaddingScheme` constructors have been remapped as follows:
- `new_oaep` => `Oaep::new`
- `new_oaep_with_label` => `Oaep::new_with_label`
- `new_oaep_with_mgf_hash` => `Oaep::new_with_mgf_hash`
- `new_oaep_with_mgf_hash_with_label` => `Oaep::new_with_mgf_hash_and_label`
- `new_pkcs1v15_encrypt` => `Pkcs1v15Encrypt`
- `new_pkcs1v15_sign` => …
=> Refactor `PaddingScheme` into a trait

Cargo.toml
Release notes: https://github.com/RustCrypto/traits/pull/1211
=> Bump `signature` crate dependency to v2

.github/workflows/ci.yml, Cargo.toml, README.md, src/key.rs
Gets rid of the `serde_crate` hacks.
Weak/namespaced features should also make it possible to make more of the functionality in this crate optional.
=> Use namespaced features for `serde`; MSRV 1.60

.github/workflows/ci.yml, Cargo.toml, README.md, src/key.rs
This reverts commit da1997d0b786181f3e3375e3eef09899486a3833.
I was probably over-eager on this: it's a breaking change.
There are probably some non-breaking changes we can make first, and when we're ready to make breaking changes again, we can revert the revert.
=> Revert "Use namespaced features for `serde`; MSRV 1.60 (#251)"

Cargo.toml, src/lib.rs, src/pkcs1v15.rs
We seem to be running into a lot of people who are having trouble with PKCS#1 v1.5 signatures because the failure mode for the `oid` feature of the `sha2` crate being disabled is fairly unscrutable.
See #234, #253, and the semi-related tracking issue for #238.
If `rsa` has a `sha2` feature, we can always ensure `oid` is enabled, and this can be used in code examples. It also means users don't need two crates to create/verify PKCS#1 v1.5 signatures.
RSA is used commonly enough with the SHA2 family that this integration probably makes sense.
cc @lumag
=> Add `sha2` feature with `oid` subfeature enabled

CHANGELOG.md, Cargo.toml
- `sha2` feature with `oid` subfeature enabled ([#255])
[#255]: https://github.com/RustCrypto/RSA/pull/255
=> rsa v0.8.1

src/lib.rs
Uses `rsa::sha2` to access `Sha256` in the code example, noting the `sha2` feature must be enabled, ala #255
=> Update PSS rustdoc example to match PKCS#1 v1.5 example

src/errors.rs, src/internals.rs, src/raw.rs
This commit prevents potential panics in internals::left_pad when the requested padded length is smaller than the input length. It also removes related dead-code in the implementation of EncryptionPrimitive for RsaPublicKey (when not panicking, the returned vector was always of length pad_size).
Feedback welcome :)
=> Fix possible panic in internals::left_pad

src/pss.rs
In the unusual case of having a key of length k*8 + 1 bits, `em_len` will be 1 byte shorter than `key_len`. The call to `raw_encryption_primitive` requires a buffer `key_len` bytes long.
Vice versa, we would be generating a one-byte too-long salt in `generate_salt`.
Finally, `emsa_pss_verify_pre` would fail by shifting 1 byte left by 8 bits.
=> Fix pss sign/verify when key length is multiple of 8 + 1 bits.

src/pkcs1v15.rs
`VerifyingKey::new` linked to `SigningKey::new_with_prefix` in the docstring; probably a copy-paste oversight.
=> Fix incorrect doc link

src/pss.rs
To create proper RsaPssParams it is necessary to determine the salt length specified for the signing key. Add a function to get it from signing keys.
=> pss: add function to get salt length from RSA PSS keys

Cargo.lock, Cargo.toml, src/pkcs1v15.rs, src/pss.rs
This is an implementation of a trait defined at https://github.com/RustCrypto/formats/pull/954
=> AssociatedAlgorithmIdentifier implementation

README.md
- Add "RustCrypto:" to crate title
- Use badge from buildstats.info that displays downloads
This is more consistent with the other READMEs in the @RustCrypto org
=> README.md: consistency fixups

src/pss.rs
The 'unsalted' PSS handling is not behaving like one would expect. It doesn't use salt of 0 length, but insteaad it uses some  defaults which are not properly documented. Make the `salt_len` mandatatory for both singing and verification.
=> Remove 'unsalted' PSS handling

src/pss.rs
This goes on top of #294 , but it is split as it is a separate feature, not directly related to usaling of the PSS.
=> pss: add random key generation for BlindedSigningKey

src/pkcs1v15.rs
Following #290, which amended `pkcs1v15::SigningKey`, this commit makes a corresponding change to `Pkcs1v15Sign` so the method name is consistent with `SigningKey::new_unprefixed`.
cc @lumag
=> Rename `Pkcs1v15Sign::new_raw` to `Pkcs1v15Sign::new_unprefixed`

src/pss.rs
Gated under the `getrandom` feature.
Calls `RandomizedSigner` with `OsRng`.
cc @lumag
=> Impl `Signer` for `pss::SigningKey`

Cargo.lock, Cargo.toml, src/pss.rs
Switch to using RsaPssParams::new() from pkcs1 crate. This fixes the issue reported by zlint for x509-cert, where SHA* digest algorithms had empty parameters instead of NULL parameters (as required by Mozilla policy and permitted by RFC4055).
=> feat: switch to RsaPssParams::new()

src/pkcs1v15.rs, src/raw.rs
This one half of #220.
Doing anything with a signature involves converting it from bytes into a `BigUint`, so this changes the inner type the latter which is more useful.
It should also help address #272, since it will enable doing those sort of checks more eagerly.
cc @lumag
=> pkcs1v15: use `BigUint` as `Signature`'s inner type

Cargo.lock, Cargo.toml
Workaround for RustCrypto/formats#1021
=> Bump `pkcs1` dependency to v0.7.5

src/pkcs1v15.rs, src/pss.rs
In both the PKCS#1v1.5 and PSS implementations, checks the signature value to ensure it does not overflow the modulus.
In the PKCS#1v1.5 implementation, checks the signature length to ensure it matches the public key size. The PSS implementation was already doing this.
Closes #272
=> Ensure signatures have right length and don't overflow

src/key.rs
Adds an impl which hashes only the public key components, along with a domain separator string (`RsaPrivateKey`).
Closes #165
=> Impl `core::hash::Hash` for `RsaPrivateKey`

Cargo.toml, src/key.rs, src/oaep.rs, src/pkcs1v15.rs, src/pss.rs
`RsaPrivateKey` self-zeroizes on drop, so add the `ZeroizeOnDrop` marker trait to `RsaPrivateKey` and all newtypes thereof, i.e. `DecryptingKey` and `SigningKey` for the various padding modes.
This also removes the `Zeroize` impl on `RsaPrivateKey`, since it self-zeroizes on `Drop`, and allowing `Zeroize` might accidentally permit use-after-zeroize vulnerabilities.
Closes #285.
=> Impl `ZeroizeOnDrop` for `RsaPrivateKey`+newtypes

src/key.rs, src/keytraits.rs, src/lib.rs
Follows RFC430 (C-CASE)
https://rust-lang.github.io/api-guidelines/naming.html
=> Rename `CRTValue` => `CrtValue`

Cargo.toml
Adds an on-by-default feature which enables `num-bigint-dig/u64_digit`.
Disabling this on 32-bit platforms (e.g. WASM) should improve performance.
Closes #252
=> Add `u64_digit` feature

src/key.rs, src/pss.rs
The `RsaPrivateKey` type previously had a `Deref` impl providing access to the associated `RsaPublicKey`.
`Deref` is intended for "smart pointer types", i.e. container types which manage a (typically generic) inner type in some way. This doesn't seem like one of those cases.
`AsRef`, on the other hand, is for cheap reference conversions, which is exactly what's happening here, so it's a better fit and provides the same functionality (albeit explicitly rather than via deref coercion).
=> Replace `Deref` impl on `RsaPrivateKey` with `AsRef`

src/pkcs1v15.rs, src/pkcs1v15/signature.rs, src/pkcs1v15/signing_key.rs, src/pkcs1v15/verifying_key.rs
This is the name for PKCS#1v1.5 signatures originally specified in RFC3447 but is also used by RFC8017 (which we cite)
=> pkcs1v15: note `RSASSA-PKCS1-v1_5` in docs

src/pkcs1v15/signature.rs, src/pss/signature.rs
The `SignatureEncoding` impl added in `rsa` v0.9 (or more specifically, the `From<Signature>` impl for `Box<[u8]>` failed to properly left pad the signatures so they matched the modulus size.
This adds the appropriate padding to the signature encoder.
=> Left pad signatures when encoding

Cargo.lock, Cargo.toml, src/pkcs1v15/signature.rs, src/pss/signature.rs
see https://github.com/RustCrypto/formats/pull/1047
=> Adds support for the `SignatureBitStringEncoding` trait

src/pkcs1v15/signature.rs
The `fmt::{LowerHex, UpperHex}` impls, with the latter called vicariously via `fmt::Display`, were showing the unpadded signature rather than the padded one.
This changes these impls to call `SignatureEncoding::to_bytes` first before displaying the signature.
=> pkcs1v15: have `fmt` impls call `SignatureEncoding::to_bytes`

CHANGELOG.md, Cargo.lock, Cargo.toml
`serde v1.0.172` and later include pre-compiled binaries which is a security hazard. So until the decision gets reverted, I believe it's worth to pin upper version of `serde`. This approach may cause issues if a different crate in someone's dependency tree will depend on a post-1.0.172 version of `serde`, but I think this issue is small enough when compared to the security concerns. Also, a number of other crates in the ecosystem follow this approach, so we are not alone.
More information and discussion about the `serde` change can be found in https://github.com/serde-rs/serde/issues/2538.
=> Pin serde to <1.0.172

CHANGELOG.md, Cargo.lock, Cargo.toml
In 1.0.184 `serde` was [un-blobbed](https://github.com/serde-rs/serde/releases/tag/v1.0.184). To prevent accidental pulling of the blobbed versions 1.0.184 will be used as a min version.
Relevant PR: #359
=> Set min version of serde to 1.0.184

README.md
Notes that the modpow implementation is not constant-time, but timing variability is masked using random blinding.
=> README.md: add notes about timing variability

.github/workflows/ci.yml
- Pins to nightly-2023-10-01 to prevent regressions
- On `minimal-versions` only uses nightly to resolve versions, and runs tests on stable instead
This is a workaround for build failures we're seeing due to a recent nightly regression. See:
https://github.com/RustCrypto/RSA/actions/runs/6655788342/job/18086838437?pr=377
https://github.com/RustCrypto/RSA/actions/runs/6655788342/job/18086838800?pr=377
=> CI: pin nightly; test minimal-versions on stable

src/algorithms/rsa.rs, src/errors.rs, src/key.rs
Based on the initial work in #258 by @davxy.
This is a first shot at implementing the algorithm laid out in : [NIST 800-56B Appendix C.2](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Br2.pdf)
=> Deterministic implementation of prime factors recovery

src/lib.rs
People were missing that the example required the `sha2` crate as a dependency. See #340.
This changes it to use the re-exported `sha2` crate and notes that the `sha2` feature must be enabled.
=> OAEP example now uses `sha2` re-export

README.md
Using `?` encourages users to properly handle errors rather than panicking.
=> README.md: use `? instead of `expect` in example

README.md
This reverts commit 00eaa91db598ad6ebe57024182e93bb82c3d75a3.
Unfortunately while `#` comments work in rustdoc, they are visible when GitHub renders the README.md, so this doesn't work.
=> Revert "README.md: use `? instead of `expect` in example (#385)"

README.md
References:
- https://github.com/RustCrypto/RSA/issues/19
- https://rustsec.org/advisories/RUSTSEC-2023-0071.html
- https://people.redhat.com/~hkario/marvin/
=> README.md: add info about Marvin Attack (RUSTSEC-2023-0071)

src/pss.rs
This returns the `AlgorithmIdentifierOwned` assuming the default situation where the salt_len is the `output_size` of the `Digest`.
This is meant to be used by HSM where the private key is hidden behind an abstraction but to still expose a `DynSignatureAlgorithmIdentifier` trait.
=> pss: expose a `get_default_pss_signature_algo_id` helper

src/pkcs1v15/signature.rs, src/pss/signature.rs
Newer versions of rustc report these. They were previously ignored because they were `pub use`, but inside of a non-`pub` module.
=> Fix unused import warnings

Cargo.toml
NOTE: not for release.
This signifies that we are going to make breaking changes to the `master` branch which are incompatible with v0.9 releases.
The first prerelease of this series published to crates.io will be v0.10.0-pre.0 at some point in the future.
=> Bump version to v0.10.0-pre

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, README.md
This makes it possible to use `rsa` with prerelease versions of `x509-cert`.
Bumps the following dependencies:
- `const-oid` v0.10.0-pre.2
- `digest` v0.11.0-pre.7
- `pkcs1` v0.8.0-pre.0
- `pkcs8` v0.11.0-pre.0
- `signature` v2.3.0-pre.2
- `sha1` v0.11.0-pre.2
- `sha2` v0.11.0-pre.2
- `sha3` v0.11.0-pre.2
- `spki` v0.8.0-pre.0
=> Bump format/signature dependencies to prereleases

marvin-toolkit/Cargo.toml, marvin-toolkit/Dockerfile, marvin-toolkit/README.md, marvin-toolkit/entrypoint.sh
This is an attempt to make the Marvin attack analysis more reproducible for `RustCrypto/RSA`. The Dockerfile and entrypoint script are both rough proofs of concept. It would be great if the maintainers can suggest how we can handle the outputs of the analysis, whether to test `rsa1024` and `rsa4096`, whether this should be part of CI/CD, among other things.
=> Marvin toolkit container

src/algorithms/oaep.rs
=> Tweak OAEP's `MAX_LABEL_LEN` constant

src/oaep.rs
As per #418, let me know if this is the preferred way or if you'd rather remove the limit some other way
=> fix: remove oaep decrypt key size limit (#418)

Cargo.lock, Cargo.toml
Bumps the following dependencies to their latest prerelease versions:
- `const-oid` v0.10.0-rc.0
- `digest` v0.11.0-pre.9
- `pkcs1` v0.8.0-rc.0
- `pkcs8` v0.11.0-rc.0
- `signature` v2.3.0-pre.4
- `spki` v0.8.0-rc.0
- `sha1` v0.11.0-pre.4
- `sha2` v0.11.0-pre.4
Note: `pkcs5` is temporarily sourced from this PR due to circular dependency problems:
https://github.com/RustCrypto/formats/pull/1461
=> Use latest prereleases

Cargo.lock, Cargo.toml, src/encoding.rs, src/pkcs1v15/signing_key.rs, src/pss/blinded_signing_key.rs, src/pss/signing_key.rs
see https://github.com/RustCrypto/formats/pull/1483
=> pkcs8 API changes

src/pss/verifying_key.rs
Some vendor serialization (NDA :() of signature and public keys will need the size of the salt that was used for signature. Sadly this is only exposed in the signing key (which may be out of reach (HSM)).
=> pss: expose salt len in the verifyingkey

src/algorithms/pkcs1v15.rs, src/key.rs
Ther are two issues with oddly formed keys that were not properly handled
- avoid using `-` to avoid a subtraction with overflow for pkcs
- always validate the key in `from_components` to avoid errors in the internal `precompute`
=> fix: handle odd keys

src/pkcs1v15/verifying_key.rs
As discussed in #341, `pkcs1v15::VerifyingKey::from` should use the prefixed keys.
Just lost a couple hours on this one behavior, and since 0.10 is just around the corner, might as well fix it before that.
Fixes #341
=> pkcs1v15: change `VerifyingKey::from` to use prefixed version

src/algorithms/oaep.rs, src/oaep.rs, src/oaep/decrypting_key.rs, src/oaep/encrypting_key.rs
This rework oaep to support non-string labels.
One use-case is encryption of secrets in TPM.
https://trustedcomputinggroup.org/wp-content/uploads/TPM-2.0-1.83-Part-1-Architecture.pdf#page=297
Section B.4 RSAES_OAEP
```
For RSA keys protecting a secret value (such as, an encryption key or a session secret), the L parameter
is a byte stream, the last byte of which must be zero, indicating the intended use of the encrypted value. 
```
That would look like:
```rust
let encrypted_seed = {
let padding = Oaep::new_with_label::<EkHash, _>(b"IDENTITY\0".to_vec());
let enc_data = ek_public
.encrypt(&mut rng, padding, &random_seed[..])
.expect("failed to encrypt");
enc_data
};
```
=> oaep: support non-string labels

src/algorithms/generate.rs
Replaces the current approximate `logf()` which we don't really need for this specific form of the argument.
Note: I am not sure why we calculate `log(2^floor(bit_size / nprimes))` while we could just as well calculate `log(2^(bit_size/nprimes))`, but I left that part intact.
=> Use a direct formula to calculate `log(2^x)`

Cargo.lock, Cargo.toml
Notably includes #394 which migrates to `crypto-bigint`
=> v0.10.0-pre.4

.github/workflows/ci.yml, .gitmodules, Cargo.lock, Cargo.toml, tests/wycheproof.rs
Thanks to @ctz who implemented a basic structure to run these in in graviola, I ported running against the relevant test vectors from https://github.com/C2SP/wycheproof
=> test: implement main test vectors from wycheproof

src/key.rs
=> fix: ensure Debug implementations do not leak private info

.github/workflows/ci.yml, Cargo.toml, src/pss/signing_key.rs
Follows the renaming in the `rand_core` crate.
=> Rename `getrandom` crate feature to `os_rng`

Cargo.lock, README.md, src/lib.rs, src/oaep.rs, src/pkcs1v15/signature.rs, src/pss/signature.rs
Hello,
This PR is not super useful BUT can be useful.
Of course this PR should be kind of reversed/updated when the rand 0.9 will be supported
Linked to 
- https://github.com/RustCrypto/RSA/issues/466
- https://github.com/RustCrypto/traits/issues/1642
- https://rustcrypto.zulipchat.com/#narrow/channel/260047-RSA/topic/rand.20dependencies/near/499002018
Feel free to close if not useful enough to be merged
=> add comment to specify the rand version

CHANGELOG.md
These versions were published as part of the `0-9-x` backport branch.
=> changelog: add entries for v0.9.7 and v0.9.8

.gitmodules
When pulling `RSA` with a `[patch.crates-io]`, the CI runner doesn't carry an SSH key with github and fails to clone the submodules.
This changes the `git@github.com` to an `https://github.com` to allow anonymous clones.
=> use a public url for git submodules

src/pkcs1v15/signing_key.rs, tests/pkcs1v15.rs
This matches https://github.com/RustCrypto/RSA/pull/472.
=> Make SigningKey::from use Self::new()

Cargo.lock, Cargo.toml, src/algorithms/rsa.rs, src/key.rs
See:
- https://github.com/RustCrypto/crypto-bigint/pull/817
=> chore(deps): bump `crypto-bigint` to `0.7.0-pre.3`; use core naming conventions

Cargo.lock, Cargo.toml, src/key.rs, src/traits/keys.rs
When serializing the exponent or the modulus from a key, `BoxedUint::to_be_bytes` will return a slice padded with zeroes on the left because of its inner representation. Not every implementation out there will handle leading zeroes.
This provides a `PublicKeyParts::n_bytes`/`e_bytes` that will strip out those leading zeros.
See https://github.com/RustCrypto/RSA/issues/518 for more context.
Depends:
- https://github.com/RustCrypto/crypto-bigint/pull/824
Fixes #518
=> PublicKeyParts: provide serialization helpers

Cargo.lock, Cargo.toml, README.md
This release is `crypto-bigint`-based and should have roughly performance parity with the previous `num-bigint`-based implementation
=> v0.10.0-rc.0

README.md
We've since migrated to `crypto-bigint`
=> README.md: remove reference to `num-bigint-dig`

src/pkcs1v15.rs, src/pkcs1v15/signing_key.rs, src/pkcs1v15/verifying_key.rs
In `rsa` v0.9 we changed these types to be prefixed-by-default, but retained and deprecated the `*_with_prefix` method names.
Now that `master` is tracking the v0.10 release, we can remove these.
=> Remove deprecated `pkcs1v15` methods

src/key.rs
It was checking the bits of precision, rather than the actual bit length of the key.
Closes #528.
=> Fix modulus size check in `check_public_with_max_size`

Cargo.lock, Cargo.toml, src/pkcs1v15.rs, src/pkcs1v15/signature.rs, src/pss.rs, src/pss/signature.rs
This notably adds `BoxedUint::from_be_slice_vartime` ~~which could be used for various public parameters, however this PR just bumps the version~~ which has been used where appropriate, namely for parsing signatures
=> Bump `crypto-bigint` to v0.7.0-pre.5

.github/workflows/workspace.yml, Cargo.toml, src/algorithms/pkcs1v15.rs, src/encoding.rs, src/errors.rs, src/key.rs, src/lib.rs, src/pkcs1v15.rs, src/pkcs1v15/signature.rs, src/pkcs1v15/signing_key.rs, src/pkcs1v15/verifying_key.rs, src/pss.rs, src/pss/blinded_signing_key.rs, src/pss/signature.rs, src/pss/signing_key.rs, src/pss/verifying_key.rs, tests/pkcs1.rs, tests/pkcs1v15.rs, tests/pkcs8.rs, tests/wycheproof.rs
Support for these formats has a number of dependencies required, and isn't always necessary, e.g. the `ssh-key` crate implements an entirely different encoding format for RSA keys.
Making support an optional feature avoids incurring these dependencies when that's the case.
This commit also removes the `pem` feature and makes PEM support on-by-default whenever `encoding` is enabled. This only adds the `pem-rfc7468` dependency. Most users will probably want PEM support if they have the `encoding` feature enabled.
=> Gate PKCS#1/PKCS#8 support on `encoding` feature

Cargo.lock, Cargo.toml, src/encoding.rs, src/errors.rs
Companion PR to RustCrypto/formats#1927 which properly composes the PKCS#8 impl in terms of the PKCS#1 impl
=> Remove PKCS#8 blanket impls for PKCS#1 traits

Cargo.lock, Cargo.toml
Bumps the following:
- pkcs1 v0.8.0-rc.3
- pkcs8 v.11.0-rc.6
- spki v0.8.0-rc.4
=> Bump format crates to latest prereleases

Cargo.toml
Don't implicitly activate them
=> rsa: weakly activate encoding deps with `std` feature

src/algorithms/pss.rs, src/pss.rs, src/pss/blinded_signing_key.rs, src/pss/signing_key.rs, src/pss/verifying_key.rs
This PR adds an optional method to automatically detect the salt length during RSA-PSS signature verification.
Should Fix: #361 and similar situations.
The crate currently requires a fixed salt length for PSS verification. This prevents verification of signatures where the salt length is not known beforehand, a situation not uncommon in interoperability contexts.
This capability was previously available but was removed in PR #294.
This change re-introduces salt length auto-detection as an explicit, opt-in feature. A new constructor, `VerifyingKey::new_with_auto_salt_len`, creates a verifier that performs this detection during verification.
*   The change is opt-in and does not affect default behavior.
*   It improves interoperability by handling signatures with variable / unknown salt …
=> PSS: Improve interoperability with optional auto salt length detection during verification

Cargo.lock, Cargo.toml
Version changes:
- `block-buffer` to `0.11.0-rc.5`
- `block-padding` to `0.4.0-rc.4`
- `cipher` to `0.5.0-rc.1`
- `crypto-bigint` to `0.7.0-rc.4`
- `crypto-common` to `0.2.0-rc.4`
- `ctr` to `0.10.0-rc.1`
- `digest` to `0.11.0-rc.1`
- `inout` to `0.2.0-rc.6`
- `salsa20` to `0.11.0-rc.1`
- `sha1` to `0.11.0-rc.2`
- `sha2` to `0.11.0-rc.2`
- `sha3` to `0.11.0-rc.2`
=> Remove patch.crates-io dependencies

src/errors.rs, src/key.rs, src/oaep/decrypting_key.rs, src/oaep/encrypting_key.rs, src/pkcs1v15/decrypting_key.rs, src/pkcs1v15/encrypting_key.rs, src/pkcs1v15/signing_key.rs, src/pkcs1v15/verifying_key.rs, src/pss/blinded_signing_key.rs, src/pss/signing_key.rs, src/pss/verifying_key.rs, tests/proptests.rs
Also adds a `hazmat`-gated `RsaPrivateKey::new_unchecked` as an escape hatch.
Partial step towards addressing #445.
cc @pinkforest
=> Add minimum `bit_size` of 1024 to `RsaPrivateKey::new`

Cargo.lock, Cargo.toml, src/pkcs1v15.rs, src/pkcs1v15/signing_key.rs, src/pkcs1v15/verifying_key.rs, src/pss.rs, src/pss/blinded_signing_key.rs, src/pss/signing_key.rs, src/pss/verifying_key.rs
This brings `*DigestSigner`/`*DigestVerifier` changes introduced in RustCrypto/traits#2004
=> Bump `signature` to v3.0.0-rc.4

Cargo.lock, Cargo.toml, src/pkcs1v15.rs, src/pss.rs, tests/wycheproof.rs
Changed tests to use the rstest #571. 
On my machine it makes the test (`--release`) run about 40% faster (2.8s to 1.6s)
Places where the pattern was `let tests = [...]` with only one test case, I changed to use rstest, since this makes adding more test cases easier. I assumed that was the reason for the `tests` variable being there despite there only being one test case.
=> rstest parametrizing for threading test cases
