RustCrypto/RSA

src/algorithms.rs
src/key.rs

Fixed up some type errors between BigInt and BigUint.

Fix BigUint incompatibilities

---

Cargo.toml

this will make the readme render on crates.io

Adding readme to Cargo.toml

---

Cargo.toml
benches/key.rs
src/key.rs

This updates all the dependencies in Cargo.toml
rand has moved some stuff around and depreciated the old location of some of their RNGs, so this update also includes using the updated RNG locations for rand.

Updating dependencies

---

Cargo.toml
src/errors.rs
src/lib.rs

Use `thiserror` instead of `failure`

---

src/internals.rs
src/key.rs
src/lib.rs
src/pkcs1v15.rs
src/raw.rs

Rebased and fixed the nit I had from #35. 
@str4d @tarcieri I think this is a good first step and am going to merge this, unless you have objections

Key trait refactor

---

README.md

README.md: remove deps.rs badge

---

.github/dependabot.yml

This bot helps to keep dependencies up to date.

chore: add Dependabot

---

README.md

Also makes the badges list a bit tidier.

Add deps.rs and chat badges

---

Cargo.toml
src/key.rs

chores: upgrade to rand-0.8

---

README.md

[this PR](https://github.com/RustCrypto/RSA/pull/119) should also be merged

docs(readme): update to match the documentation example

---

Cargo.toml

chore(deps): Update crypto crates 

---

Cargo.toml

Prerelease to assist in debugging #146 and to unblock people waiting on a final v0.6.0 release

v0.6.0-pre

---

src/oaep.rs
src/pkcs1v15.rs

Mark plaintexts which are about to be encrypted as zeroizing

---

src/internals.rs
src/key.rs
src/pkcs1v15.rs
src/pss.rs

cleanup: resolve numerous clippy lints

---

src/pkcs1v15.rs
src/pss.rs

feat: impl AsRef for Signing/Verifying keys

---

src/pkcs1v15.rs
src/pss.rs

feat: impl From for Signing/Verifying keys

---

src/pss.rs

feat: derive(Debug, Copy) for pss::BlindedSigningKey

---

src/pkcs1v15.rs
src/pss.rs

feat: enable extracting the inner key type

---

src/pkcs1v15.rs
src/pss.rs

Implement encoding Signing keys to PKCS#8 DER format.

feat: add support for EncodePrivateKey

---

README.md
src/lib.rs

I wanted to test this crate using the example in the readme, but it failed, so
here in an updated README so that it builds.
I also included the README example among the doctests, so that it keeps up in the future.
I did find updated documentation on https://docs.rs/rsa/latest/rsa/ so it seems just this file
has been out of date.

Updating README example

---

README.md

README.md: link to officially hosted audit report

---

src/lib.rs

Automatically document feature-gated functionality

Use `doc_auto_cfg`

---

src/key.rs

Adds the following checks:
- `n` is odd
- `e` is odd
- `e` < `n`
Closes #99

Improved public key checks

---

Cargo.lock
Cargo.toml
tests/proptests.rs

Adds proptests for RSASSA-PKCS1-v1_5 and RSA-PSS.
NOTE: these are currently expected to fail, and to be resolved by #325

Initial proptests

---

src/algorithms/generate.rs

See #343 where it wasn't entirely clear

Add clarifying comment for totient check in key generation

---

benches/key.rs

Variation is high unfortunately, but at least it's something

bench: add key gen benchmarks
